# Common Homebrew location on Apple Silicon:
APPIUM_JS_PATH=/opt/homebrew/lib/node_modules/appium/index.js

# Application paths. Leave unused platforms empty.
APP_ANDROID_DEVICE_PATH=/absolute/path/to/application.apk
APP_IOS_REAL_DEVICE_PATH=/absolute/path/to/real-device-application.app
APP_IOS_EMULATOR_PATH=/absolute/path/to/simulator-application.app
